### ISSUE TITLE
Suggestion: augment existing type declarations

### ISSUE THREAD

**Issue by danvk** [g-plane/typed-query-selector#1]
Rather than shipping a distinct runtime `querySelector` function, it should be possible to distribute a `queryselector.d.ts` that overloads the existing global definitions for `querySelector` in `lib.dom.d.ts`. Then you could install this library and get better typings without ever thinking about it again. This might require users to add something to their `tsconfig.json`, I'm not 100% sure.

**Comment by g-plane** [comment]
Thanks for your idea! I'm investigating it.
