### ISSUE TITLE
detect mistake in selector

### ISSUE THREAD

**Issue by Manu1400** [g-plane/typed-query-selector#11]
```typescript
import type { ParseSelector } from 'typed-query-selector'

type C = ParseSelector<'dialog.'>;
```

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBDAnmApnA3nACgQygZxQGUUAbFAYxmjgF84AzKCEOAciVQBMBaARwCuKKIh6FyVaGwBQ0zmgDCcALzY8hEhOpQAPGy7AcpCAHMAdGwB8AbiA

Actual : `type C = HTMLDialogElement`
Expected : detect the mistake (and return `HTMLUnknownElement` or `Element ` ?)

**Comment by g-plane** [comment]
Thanks for your report! I'll fix it.
