### ISSUE TITLE
Return type parameter in querySelector shim can cause undesired casts

### ISSUE THREAD

**Issue by brendankenny** [g-plane/typed-query-selector#12]
The type parameter `E` in the `querySelector`/`querySelectorAll` shim:

https://github.com/g-plane/typed-query-selector/blob/823e4b850280dab7192cd0468b8e97c196e9e8ec/shim.d.ts#L5-L7

can cause undesired type casts depending on the context of use. The problem is that the type parameter `E` is used _only_ in the return type. If the context provides a type that extends `Element`, the compiler will happily use that instead of the default of `ParseSelector<S>`.

For example:

```ts
const anchor: HTMLAnchorElement|null = document.querySelector('div'); // No error.
// querySelector type is `ParentNode.querySelector<"div", HTMLAnchorElement>(selector: "div"): HTMLAnchorElement | null`
```

```ts
const results: Array<HTMLAnchorElement|null> = [];
results.push(document.querySelector('div')); // No error (querySelector type is same as above).
```

On the other hand, this feature allows the [element type overriding feature](https://github.com/g-plane/typed-query-selector/tree/823e4b850280dab7192cd0468b8e97c196e9e8ec#web-components), like in

```ts
document.querySelector<MyComponent>('my-web-component') // ==> MyComponent
```

so I'm not sure what the best fix would be (if any). It's also easy enough for users of the library to do their own 

```ts
querySelector<S extends string>(selector: S): ParseSelector<S> | null;
```

shim if that's their preferred functionality.

**Comment by g-plane** [comment]
I found that even we put `ParseSelector<S>` as return type, overriding still works.

**Comment by g-plane** [comment]
Fixed in [v2.4.1](https://github.com/g-plane/typed-query-selector/blob/master/CHANGELOG.md#v241) .

**Comment by 864msk** [comment]
> معلمة النوع `E`في `querySelector`/ `querySelectorAll`shim:
> 
> https://github.com/g-plane/typed-query-selector/blob/823e4b850280dab7192cd0468b8e97c196e9e8ec/shim.d.ts#L5-L7
> 
> يمكن أن تتسبب في أشكال غير مرغوب فيها من النوع اعتمادًا على سياق الاستخدام. المشكلة هي أن معلمة النوع `E`تستخدم _فقط_ في نوع الإرجاع. إذا كان السياق يوفر نوعًا يمتد `Element`، فسيستخدمه المترجم بسعادة بدلاً من الافتراضي `ParseSelector<S>`.
> 
> على سبيل المثال:
> 
> ```ts
> CONST  مرساة : HTMLAnchorElement | خالية  =  وثيقة . querySelector ( 'div' ) ؛  // لا يوجد خطأ. 
> // querySelector type هو `ParentNode.querySelector <" div "، HTMLAnchorElement> (المحدد:" div "): HTMLAnchorElement | خالية
> ```
> 
> ```ts
>  نتائج const : صفيف < HTMLAnchorElement | خالية >  =  [ ] ؛ 
> النتائج . push ( document . querySelector ( 'div' ) ) ؛  // لا يوجد خطأ (نوع محدد الاستعلام هو نفسه كما هو مذكور أعلاه).
> ```
> 
> من ناحية أخرى ، تسمح هذه الميزة لميزة [تجاوز نوع العنصر](https://github.com/g-plane/typed-query-selector/tree/823e4b850280dab7192cd0468b8e97c196e9e8ec#web-components) ، كما هو الحال في
> 
> ```ts
> وثيقة . querySelector < MyComponent > ( 'my-web-component' )  // ==> MyComponent
> ```
> 
> لذلك لست متأكدًا من أفضل حل (إن وجد). من السهل أيضًا أن يقوم مستخدمو المكتبة بعمل أعمالهم الخاصة
> 
> ```ts
> محدد الاستعلام < S  يوسع السلسلة > ( المحدد : S ) : ParseSelector < S > | لاغية ؛
> ```
> 
> shim إذا كانت هذه هي وظيفتهم المفضلة.
