### ISSUE TITLE
Add support for `:is()` and other functions

### ISSUE THREAD

**Issue by fregante** [g-plane/typed-query-selector#13]
`:is(a,link)` doesn’t seem to be supported. There’s also `:where()` which works almost identically

**Comment by g-plane** [comment]
It seems that there aren't differences between `:is` and `:where` for parsing CSS selector, right?

**Comment by fregante** [comment]
Thank you for the quick fix!

**Comment by g-plane** [comment]
However, there's a bug when you use more that one `:is` or `:where` and I'm trying to fix it.

**Comment by fregante** [comment]
It's good to test also if it works with `:is():not()`

**Comment by g-plane** [comment]
https://github.com/g-plane/typed-query-selector/commit/f51424553160435819cfb8a964de067522723087

**Comment by g-plane** [comment]
[v2.5.0](https://www.npmjs.com/package/typed-query-selector/v/2.5.0) is released. Feel free to provide feedback.

**Comment by fregante** [comment]
cc @yakov116

**Comment by yakov116** [comment]
This made me more issues then it solved 😢 

https://github.com/sindresorhus/refined-github/actions/runs/759870212

**Comment by g-plane** [comment]
@yakov116 Please follow #14 .
