### ISSUE TITLE
Regression: bug for fallback type

### ISSUE THREAD

**Issue by g-plane** [g-plane/typed-query-selector#14]
> This made me more issues then it solved 😢 

https://github.com/sindresorhus/refined-github/actions/runs/759870212

_Originally posted by @yakov116 in https://github.com/g-plane/typed-query-selector/issues/13#issuecomment-821924145_

**Comment by g-plane** [comment]
@yakov116 [v2.5.1](https://www.npmjs.com/package/typed-query-selector/v/2.5.1) is released.

**Comment by yakov116** [comment]
Thanks for the quick response!
