### ISSUE TITLE
issue:is(there any thing you can do here)

### ISSUE THREAD

**Issue by yakov116** [g-plane/typed-query-selector#15]
2.5.1 fixed the fallback thanks!

I am having an issue that 

```css
:is(a[selector], a[selector]) <--- works

a:is(selector, selector) <--- does not
```
results in `never[]`

see https://github.com/sindresorhus/refined-github/runs/2377156010

Thanks

**Comment by g-plane** [comment]
[v2.5.3](https://www.npmjs.com/package/typed-query-selector/v/2.5.3) is released. (v2.5.2 has a mistake so don't use it.)

**Comment by yakov116** [comment]
Thanks!!
