### ISSUE TITLE
is `.closest` supported?

### ISSUE THREAD

**Issue by yakov116** [g-plane/typed-query-selector#16]

**Comment by g-plane** [comment]
Can you provide more details? (For example, MDN documentation link)

**Comment by yakov116** [comment]
`document.querySelector('a').closest('img')` currently we have to do `.closest<HTMLImgElement>('img')`

**Comment by g-plane** [comment]
Sorry for delay! [v2.6.0](https://www.npmjs.com/package/typed-query-selector/v/2.6.0) is released.

**Comment by yakov116** [comment]
Awesome!! your so fast!

**Comment by yakov116** [comment]
Could the default fallback be HTMLElement?

**Comment by g-plane** [comment]
I think we should keep align with TypeScript's built-in types.

**Comment by yakov116** [comment]
ok how would I set that in my project (sorry I don't really know typescript [yet])

**Comment by g-plane** [comment]
Are there any use cases or examples?

**Comment by yakov116** [comment]
https://github.com/sindresorhus/refined-github/pull/4276/checks?check_run_id=2454302281

**Comment by g-plane** [comment]
I may need to investigate usage and try to find a solution.

`HTMLElement` contains some properties which `Element` doesn't, so we can't replace it directly.

**Comment by fregante** [comment]
What do you think about exporting a file that defaults to HTMLElement for both querySelector and closest? So I can use `import 'typed-query-selector/html'`

**Comment by g-plane** [comment]
I also thought about that several months ago, but the reason why I didn't do it finally is that there's already `'typed-query-selector/strict'`, and what about some users want both `strict` and `html`? I was looking for an elegant solution to mix them, but it's hard.

**Comment by fregante** [comment]
That's alright, I ended up copy-pasting shim.d.ts and adjusting it. Thanks a lot for this package!
