### ISSUE TITLE
Install this package as DefinitelyTyped

### ISSUE THREAD

**Issue by zuhairtaha** [g-plane/typed-query-selector#24]
Is it possible to make this package a [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) package
Then we can install it as `@types/query-selector` for example.

**Comment by zuhairtaha** [comment]
No. I can use it, but just wonder. 
I like it. It is amazing.

**Comment by g-plane** [comment]
There shouldn't be any differences, so I think we don't need to do that.
