### ISSUE TITLE
Some `:is()` selectors are failing

### ISSUE THREAD

**Issue by fregante** [g-plane/typed-query-selector#26]
<img width="558" alt="Screen Shot 7" src="https://user-images.githubusercontent.com/1402241/189194354-bd872860-04e7-4f52-a99e-9e68450a5f30.png">

I don't know if it's my override, but both of these are producing `HTMLElement`:

```ts
const a = document.querySelector(`a.status-actions:is([href^="/"])`);
const b = document.querySelector(`a.status-actions:is(a[href^="/"])`);

```

I don't know if I'm doing something wrong in my override:

https://github.com/refined-github/refined-github/blob/65c58aed2ceb98e50c9112e7ef0428821033742e/source/helpers/types.d.ts#L5:L5

This issue appeared after updating to TS 4.8 I think, as well as typed-query-selector v2.7

**Comment by g-plane** [comment]
Should they produce `HTMLAnchorElement`?

**Comment by g-plane** [comment]
It would be hard to detect whether we should use the selector inside `:is` or not. For example:

```css
*:is(a) {}

a:is(*) {}
```

Both can match `<a>` element, but for parser, there's no good way to detect it.

**Comment by fregante** [comment]
I don't know about the parser, but definitely the selector can only match only `a`. 

Why can't they detect the right type? I think I've seen them work before 🤔

**Comment by g-plane** [comment]
It would be splitted into two parts: `*` and `a`, and it can be hard to decide to select which one.

**Comment by papb** [comment]
If the part to the left of the colon specifies a type `X` and the part inside parens specifies a type `Y`, shouldn't `X & Y` be returned then? In this case, `HTMLElement & HTMLAnchorElement` would simplify to `HTMLAnchorElement`.

**Comment by g-plane** [comment]
Yes, I know that fact. But, in intermediate phase of the parser, it can't be able to resolve tag name string to corresponding types.

**Comment by papb** [comment]
> But, in intermediate phase of the parser, it can't be able to resolve tag name string to corresponding types.

Why not?

(really trying to understand to see if maybe I can help coming up with a solution)

**Comment by g-plane** [comment]
Resolving tag name string to types is the last phase. Before that, it just processes strings.

**Comment by fregante** [comment]
Similar issue, but different. This works:

```ts
const ok: HTMLAnchorElement | null = document.querySelector(`a:is([href*="/issues"], [href*="/pulls"], [href*="/projects"], [href*="/labels/"]):not([href*="sort%3A"], .issues-reset-query)`);
```

But if you any whitespace inside `:is` at the wrong place, it stops inferring the type correctly

For example, 


```ts
const nope: HTMLAnchorElement | null = document.querySelector(`a:is(
[href*="/issues"], [href*="/pulls"], [href*="/projects"], [href*="/labels/"]):not([href*="sort%3A"], .issues-reset-query)`);
```

Or even just a space after `:is(`

**Comment by g-plane** [comment]
This has been fixed in https://github.com/g-plane/typed-query-selector/commit/85119cd44d4522ab101645d0ce0d3ca9d1c8a9c6 .

**Comment by g-plane** [comment]
@fregante Is it reasonable if I write selectors like this?

```shell
a:is(b, c) # different tag names
```

**Comment by fregante** [comment]
That will never match anything, because h1 can't also be h2.

These are possible:

```css
h1:is(*)
h1:is(.c)
.c:is(h1)
:is(h1,h2):is(.c) 
```

**Comment by g-plane** [comment]
New version will be released tomorrow. Note that `:is(h1,h2):is(.c)` isn't supported due to OOM when type checking.

**Comment by g-plane** [comment]
https://github.com/g-plane/typed-query-selector/releases/tag/v2.8.1

**Comment by fregante** [comment]
These two instances were not fixed, I'm not sure if it's due to :is() or :not()

https://github.com/refined-github/refined-github/blob/60ac04e85cdb0c597e90d3d314ad6fb4c1fe4d8d/source/features/show-names.tsx/#L76

https://github.com/refined-github/refined-github/blob/60ac04e85cdb0c597e90d3d314ad6fb4c1fe4d8d/source/features/sort-conversations-by-update-time.tsx/#L71

See https://github.com/refined-github/refined-github/pull/6370

**Comment by g-plane** [comment]
I can re-produce the second one.

**Comment by fregante** [comment]
Indeed it's caused by my `css` helper

**Comment by g-plane** [comment]
I've rewritten the logic, and these inputs are supported:

- `:is(h1,h2):is(.c)` (previously this will cause OOM)
- https://github.com/refined-github/refined-github/blob/60ac04e85cdb0c597e90d3d314ad6fb4c1fe4d8d/source/features/show-names.tsx/#L76

You can inspect the tests: https://github.com/g-plane/typed-query-selector/commit/ff8b92c3fd1a23be4efbb60c4a2a01fc85d40736#diff-dd001b5fbb36c7c3308e20c616e78502244a6be3a772c85a58cb3d8e3f84d55f .

It should work better than before when parsing `:is()` and `:where()`.
