### ISSUE TITLE
Allow setting the Fallback via global

### ISSUE THREAD

**Issue by fregante** [g-plane/typed-query-selector#29]
The current solution to change the fallback from `Element` to `HTMLElement` is to copy the contents of [the shim](https://github.com/g-plane/typed-query-selector/blob/b1f4f22faa3967bd61af9c1f2b750bb6d96d7997/shim.d.ts) and make a change, like I did in https://github.com/refined-github/refined-github/blob/71c16f38d5d7853e57bd3e36852175b30eed89c3/source/helpers/types.d.ts#LL7

This also currently isn't possible in the strict parser:

- #28 

What do you think about using a global like `SelectorFallback` in this module so that I can override it globally by just using:

```ts
// global.d.ts

declare SelectorFallback = HTMLElement;
```

**Comment by g-plane** [comment]
If I remember, TypeScript wouldn't allow you to re-declare something.

**Comment by g-plane** [comment]
After https://github.com/g-plane/typed-query-selector/releases/tag/v2.9.0 , you don't need that helper to shim `HTMLElement` any more.

**Comment by fregante** [comment]
In the end I didn't use this because I had altered my types to accept arrays of selectors too: `el.closest(['a', 's'])` which is technically wrong, but it works (because `['a', 's'].toString() === 'a,s'`)

https://github.com/refined-github/refined-github/blob/714f51c81394b2186c40b5ee1248663f12293fe5/source/helpers/types.d.ts/#L10

However 4534a0c isn't technically correct because any HTML5 document can still contain SVG tags. Try this on https://developer.mozilla.org/en-US/

```js
document.querySelector('svg') instanceof HTMLElement // => false
```
```js
document.querySelector('svg') instanceof SVGElement // => true
```

**Comment by fregante** [comment]
In practice however this only happens when both of these are true:

- `typed-query-selector` fails to parse the selector (or is dynamic)
- the user actually selects an element inside SVG (rare)

**Comment by g-plane** [comment]
Oh, I didn't realize that. You're right, but we can leave it and re-consider it once we receive feedback about the types.

**Comment by stof** [comment]
This also happens if the user selects inside MathML (which does not use HTMLElement either).

It would be great to move those "unsafe" fallbacks to a separate shim file to make them opt-in

**Comment by stof** [comment]
@g-plane is there any plan to split those unsafe fallbacks to a separate shim ?

**Comment by fregante** [comment]
It's better to revert this change and default to `Element` for correctness

**Comment by stof** [comment]
I'm also fine with a complete revert, as that would bring back correctness

**Comment by g-plane** [comment]
It's reverted in v2.10.0.

**Comment by stof** [comment]
Thanks
