### ISSUE TITLE
It doesn't seem to support all attribute selector contents

### ISSUE THREAD

**Issue by fregante** [g-plane/typed-query-selector#3]
I'm looking to use these types in my [querySelector wrapper module](https://github.com/fregante/select-dom/pull/15) but in my tests it seems that the `+` character is not supported in attributes:
```ts
'link[type="application/json"]' => HTMLLinkElement
'link[type="application/atom+xml"]' => Element
```

I wonder what other characters can create problems

**Comment by g-plane** [comment]
The reason is `+` is a selector combinator, then it treats `xml"]` as unparsed string.

**Comment by fregante** [comment]
Should it be escaped? When quoted, the selector works
