### ISSUE TITLE
Regression since 2.9.0

### ISSUE THREAD

**Issue by falsandtru** [g-plane/typed-query-selector#32]
This code causes an error since 2.9.0.

```ts
import 'typed-query-selector'

function f<T extends HTMLElement>(s: string) {
    document.querySelector<T>(s);
}
```

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAchgTzAUwCYFoCOBXNKZLAZzQBs0BjGaBAKHoDM8A7G4CVuJgHgBU4aAB4w0rDCTgAJfgFkAMgFFKIcTAB8AChIAuOCRhRgrAOYBKOAG96cO3AwQqeNaxgA6fIWQBlCtVooAW0ScwBuegBfIA

**Comment by fregante** [comment]
What are you trying to accomplish?  If you just want a shortcut for `document.querySelector` you'll have to rewrite that. I think:

```ts 
const f = document.querySelector.bind(document)
```

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAchgTzAUwCYFoCOBXNKZLAZzQBs0BjGaBAKHqogDsT4AzOAXjgwip4QaFjAB0+QsgDKFarShiARsBYYAFP0HDRASgDcTVuzgAPHnA7qEGYADc4JOwHMxzCOTjOEu+nH9wAPSBAHoA-EA

**Comment by falsandtru** [comment]
Passing HTMLElement type is a standard usage of a standard type definition. Custom definitions must not prevent standard usages. Anyway, `document.querySelector<HTMLElement>(s)` is also an error.

**Comment by fregante** [comment]
> Custom definitions must not prevent standard usages. 

Says who? There is not such rule.

The whole point of this package is to avoid having to specify types.

Again, what are you trying to accomplish with that piece of code?

**Comment by falsandtru** [comment]
https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAchgTzAUwCYFoCOBXNKZLAZzQBs0BjGaBAKHowirxDQDsYA6fQ5AMoVqtKAB4AEgBUAsgBkAopXZcAfAAoE3KuQCGJEh13sEASgDcQA

**Comment by fregante** [comment]
That answers none of my questions, I already know how that works

**Comment by falsandtru** [comment]
Pointless questions. Impossible to justify inhibiting this most standard usage by your questions.

**Comment by fregante** [comment]
I agree it would be nice to keep that, but when debugging those are the most basic questions to ask: why? 

Also what you're saying is plain wrong, so there's that.

**Comment by falsandtru** [comment]
> Also what you're saying is plain wrong, so there's that.

Of course I understand you didn't explain why and how it's wrong because you couldn't explain it.
