### ISSUE TITLE
ParseSelector return unknown in its return type instead of always using the fallback type when using TS 5.4

### ISSUE THREAD

**Issue by stof** [g-plane/typed-query-selector#36]
See https://github.com/fregante/delegate-it/issues/50 (and https://github.com/fregante/delegate-it/pull/51 which runs the testsuite with typescript 5.4).
See also https://github.com/g-plane/typed-query-selector/commit/ed964d1f1773905b64f99a68d4b8e54b4a326fe9#r139690533 where the discussion started.

To me, the change in the `querySelectorAll` type in that commit should not exist. It is a workaround for the fact that `ParseSelector` now returns `unknown` while it should never do it.
My intuition is that `ExpandAnd` is the one not properly handling the fallback.

**Comment by g-plane** [comment]
You can try `ParseSelector<':is(a,)'>` which is an invalid selector, and it returns `Element`.

**Comment by stof** [comment]
The case where this happens is not when having a known selector in ParseSelector but when defining a generic function (i.e. the same case than `querySelectorAll` in your commit, or in delegate-it)

**Comment by stof** [comment]
i.e. a case where we don't know whether we will have to use the fallback or a parsed type, but having both branches of the union.

**Comment by stof** [comment]
see https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBDAnmApnA3nACgQygZxQGUUAbFAYxmjgF84AzKCEOAciVQBMBaARwCuKKIh6FyVaAHoweQlDYAoRQwEA7KsAhq4XMigDmOGCgA8JCdShwUADxNqu+OPhhRgagwBo4AFQCi5CAoavB2Dk5wgSjBoXAAvNhyxPqSUOapVj4AEr4AsgAy0bEwAHwAFOKUVgBccBbV0ACUGMq0QA

`ParseSelector<Selector, HTMLElement>` does not satisfy `Element`

**Comment by fregante** [comment]
It worked, thank you!

https://github.com/fregante/delegate-it/pull/51
