### ISSUE TITLE
How to override the parsed type?

### ISSUE THREAD

**Issue by fregante** [g-plane/typed-query-selector#4]
Dynamic strings can't be parsed by TypeScript, so overrides are necessary, but the regular `querySelector<MyOverrideElement>(variable)` no longer works.

**Comment by g-plane** [comment]
This should work automatically because it's just a function overload of TypeScript and it does nothing for the `string` type.

**Comment by fregante** [comment]
Unfortunately the first argument has to match the first generic, so `query<'div'>('something')` fails

**Comment by g-plane** [comment]
This is invalid, because your `'div'` at type parameter doesn't match any overloads.

**Comment by fregante** [comment]
Can you show your suggested solution in #6?

**Comment by fregante** [comment]
I’ll have to review my own types, for now it appears to work 😅
