### ISSUE TITLE
Support array of selectors by default

### ISSUE THREAD

**Issue by fregante** [g-plane/typed-query-selector#41]
JavaScript is cool: `document.querySelector(['a', 'b'])` works out of the box because arrays are stringified as `a,b`, which happens to be a valid selector.

I prefer arrays of selectors (`['a', 'b']`) over selector list strings (`'a, b'`) because they can be documented/commented better and can be wrapped/formatted automatically. 

This is why I generally have code like this in all of my projects:

```ts
import type {StrictlyParseSelector} from 'typed-query-selector/parser.js';

declare global {
	interface ParentNode {
		querySelector<S extends string>(selector: S | readonly S[]): StrictlyParseSelector<S, HTMLElement> | null;

		querySelectorAll<S extends string>(
			selector: S | readonly S[],
		): NodeListOf<StrictlyParseSelector<S, HTMLElement>>;
	}

	interface Element {
		closest<S extends string>(selector: S | readonly S[]): StrictlyParseSelector<S, HTMLElement> | null;
		matches(selectors: string | readonly string[]): boolean;
	}
}
```

### Proposal

Would you be open to _loosening_ `typed-query-selector` by default to allow `string | string[]` as the input?

Adding another `/with-arrays.d.ts` (and `/strict-with-arrays.d.ts`) would also work, but it would increase the amount of code to maintain.

### Related

- `querySelector` wrapper with array of selectors: https://github.com/fregante/select-dom/blob/afdd637791737fc9dbcc8590d6655246d16bb4d5/index.ts#L18-L19
- Event delegation with array of selectors: https://github.com/fregante/delegate-it/issues/35
- Selector watcher with array of selectors: https://github.com/refined-github/refined-github/blob/6e167b9d881bd05db8cb92a5e140144cda7fd873/source/helpers/selector-observer.tsx#L49
- Lint rule to prefer arrays: https://github.com/refined-github/refined-github/pull/7696

**Comment by g-plane** [comment]
This is a hack and personally I wouldn't like to add it. And yes, you can implement it in downstream as you did.
