### ISSUE TITLE
Multiline selectors aren't supported

### ISSUE THREAD

**Issue by fregante** [g-plane/typed-query-selector#5]
Sorry for the many issues! I found another one:

```ts
document.querySelector(`
button`) // -> Element
```

**Comment by g-plane** [comment]
This should be fixed easily. Thanks for your suggestions.

**Comment by g-plane** [comment]
v2.1.1 is released! Feel free to open issues if you find more problems.

**Comment by fregante** [comment]
I think that this doesn't support tabs. Example:

```js
document.querySelector(`
button`) // HTMLButtonElement | null

document.querySelector(`
	button`) // Element | null
```

**Comment by g-plane** [comment]
Is there spec about this? When I try in browser console, selector string with tabs is allowed.

**Comment by fregante** [comment]
> Is there spec about this?

It's the CSS spec. Whitespace is ignored everywhere (except inside compound selectors)

> When I try in browser console, selector string with tabs is allowed

Yes, both example work; Just the types need to be fixed.

**Comment by g-plane** [comment]
Fixed in https://github.com/g-plane/typed-query-selector/commit/ecb02e6b000b26f4c0c7c6a9aedcba772c24481d .
